var genres = {
  punk: {
    Extraverted: 0.5,
    Intuitive: 1,
    Tinking: 0.5,
    Judging: 0,
    Assertive: 0,
    Introverted: 0,
    Observant: 0,
    Feeling: 0.5,
    Prospecting: 1,
    Turbulent: 0.5
  }, 
  jazz: { 
    Extraverted: 1,
    Intuitive: 1,
    Tinking: 0.5,
    Judging: 0.5,
    Assertive: 1,
    Introverted: 0,
    Observant: 0,
    Feeling: 0.5,
    Prospecting: 0.5,
    Turbulent: 0
  }, 
  classical: { 
    Extraverted: 0.5,
    Intuitive: 1,
    Tinking: 0.5,
    Judging: 0.5,
    Assertive: 1,
    Introverted: 0.5,
    Observant: 0,
    Feeling: 0.5,
    Prospecting: 0.5,
    Turbulent: 0
  },
  rock: { 
    Extraverted: 0.5,
    Intuitive: 1,
    Tinking: 0.5,
    Judging: 0,
    Assertive: 0.5,
    Introverted: 0.5,
    Observant: 0,
    Feeling: 0.5,
    Prospecting: 1,
    Turbulent: 0.5
  },
  'alternative rock': { 
    Extraverted: 0.5,
    Intuitive: 1,
    Tinking: 0,
    Judging: 0,
    Assertive: 0,
    Introverted: 0.5,
    Observant: 0,
    Feeling: 1,
    Prospecting: 1,
    Turbulent: 1
  },
  reggae: { 
    Extraverted: 1,
    Intuitive: 0.5,
    Tinking: 0,
    Judging: 0.5,
    Assertive: 1,
    Introverted: 0,
    Observant: 0.5,
    Feeling: 1,
    Prospecting: 0.5,
    Turbulent: 0.5
  },
  ambient: { 
    Extraverted: 0.5,
    Intuitive: 1,
    Tinking: 0,
    Judging: 0,
    Assertive: 0.5,
    Introverted: 0.5,
    Observant: 0,
    Feeling: 1,
    Prospecting: 1,
    Turbulent: 0.5
  },
  world: { 
    Extraverted: 0.5,
    Intuitive: 1,
    Tinking: 0,
    Judging: 0.5,
    Assertive: 0.5,
    Introverted: 0.5,
    Observant: 0,
    Feeling: 1,
    Prospecting: 0.5,
    Turbulent: 0.5
  },
  pop: { 
    Extraverted: 1,
    Intuitive: 0,
    Tinking: 0,
    Judging: 0.5,
    Assertive: 0,
    Introverted: 0,
    Observant: 1,
    Feeling: 1,
    Prospecting: 0.5,
    Turbulent: 1
  },
  metal: { 
    Extraverted: 0,
    Intuitive: 1,
    Tinking: 1,
    Judging: 0,
    Assertive: 0.5,
    Introverted: 1,
    Observant: 0,
    Feeling: 0,
    Prospecting: 1,
    Turbulent: 0.5
  }, 
  'hip hop': { 
    Extraverted: 1,
    Intuitive: 0.5,
    Tinking: 0.5,
    Judging: 0,
    Assertive: 0.5,
    Introverted: 0,
    Observant: 0.5,
    Feeling: 0.5,
    Prospecting: 1,
    Turbulent: 0.5
  },
  electronica: { 
    Extraverted: 1,
    Intuitive: 1,
    Tinking: 0.5,
    Judging: 0,
    Assertive: 0.5,
    Introverted: 0,
    Observant: 0,
    Feeling: 0.5,
    Prospecting: 1,
    Turbulent: 0.5
  },
  religious: { 
    Extraverted: 0.5,
    Intuitive: 0,
    Tinking: 0,
    Judging: 1,
    Assertive: 0.5,
    Introverted: 0.5,
    Observant: 1,
    Feeling: 1,
    Prospecting: 0,
    Turbulent: 0.5
  },
  blues: { 
    Extraverted: 1,
    Intuitive: 1,
    Tinking: 0.5,
    Judging: 0.5,
    Assertive: 1,
    Introverted: 0,
    Observant: 0,
    Feeling: 0.5,
    Prospecting: 0.5,
    Turbulent: 0
  },
  country: { 
    Extraverted: 1,
    Intuitive: 0,
    Tinking: 0,
    Judging: 0.5,
    Assertive: 0.5,
    Introverted: 0,
    Observant: 1,
    Feeling: 1,
    Prospecting: 0.5,
    Turbulent: 0.5
  },
  soul: { 
    Extraverted: 1,
    Intuitive: 0.5,
    Tinking: 0,
    Judging: 0.5,
    Assertive: 0.5,
    Introverted: 0,
    Observant: 0.5,
    Feeling: 1,
    Prospecting: 0.5,
    Turbulent: 0.5
  },
  'indie pop': { 
    Extraverted: 0.5,
    Intuitive: 1,
    Tinking: 0,
    Judging: 0.5,
    Assertive: 0,
    Introverted: 0.5,
    Observant: 0,
    Feeling: 1,
    Prospecting: 0.5,
    Turbulent: 1
  },            
};

module.exports = genres;